version: 2.1

orbs:
  dotnet: circleci/windows@5
  docker: circleci/docker@2.6.0

workflows:
  build-only:
    jobs:
      - docker/check
      - docker/build:
          image: $CIRCLE_PROJECT_USERNAME/CIRCLE_PROJECT_REPO
          tag: $CIRCLE_SHA1
          attach-at: ./
          update-description: true

