version: 2.1
orbs:
  dotnet: circleci/windows@5
  docker: circleci/docker@2.6.0

jobs:
  build-only:
    executor: docker/docker
    steps:
      - docker/check:
          docker-username: DOCKER_USERNAME
          docker-password: DOCKER_PASSWORD
      - checkout
      - docker/build:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPO
          tag: $CIRCLE_SHA1
          attach-at: ./

workflows:
  build:
    jobs:
      - build-only

